### PR TITLE
On 64-bit Windows install 64-bit Python 2.7.14

### PR DESCRIPTION
**Pull request by j3hill**
### Description

Check for 64-bit Windows and install 64-bit Python 2.7.14. Otherwise, install 32-bit Python 2.7.14. 
Modify the "download-prerequisites.ps1" PowerShell script to support downloads with TLS, and update the Mbed CLI version to 1.10.0.

### Pull request type

    [ ] Fix
    [ ] Refactor
    [ ] Target update
    [x] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

### CODE REVIEW

**Comment by j3hill** [comment]
@theotherjimmy  Who should review this change?

**Comment by theotherjimmy** [comment]
@arekzaluski Is probably the best person to review.

**Comment by j3hill** [comment]
These changes should also help with this issue: https://github.com/ARMmbed/cmsis-pack-manager/issues/86

**Pull request merged**
